name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # Only deploy when changes are pushed to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload  # Specify the deployment action
          app_location: "/"  # Adjust path as necessary
          output_location: ""  # Adjust path as necessary
